### ISSUE TITLE
Створити макети сайту

### ISSUE THREAD

**Issue by KhilchenkoYurii** [KhilchenkoYurii/InterActiMate#1]

**Comment by Solomiia27** [comment]
@YaroslavKuziv1999 зміни, будь ласко, в макеті назви на InterActiMate, якщо правильно пам.ятаю, то ми вирішили, що воно так більш читабельно буде

**Comment by KhilchenkoYurii** [comment]
@YaroslavKuziv1999 ти вніс зміни, про які писала Соломія?

**Comment by Solomiia27** [comment]
Треба додати щось типу "Проект InerActiMate створений в межах програми UPSHIFT за підтримки ЮНІСЕФ та уряду Німеччини через німецькі державний банк розвитку KFW" та їх лого, це вимога від апшифта на період оцього гранту

**Comment by KhilchenkoYurii** [comment]
@YaroslavKuziv1999  Дороби будь ласка ось ці пункти
- Прибрати іконку будиночка (З усіх сторінок)
- Забрати Кнопки Чат і Додати оголошення в Guest (Для сторінок де буде роль користувача Guest )
- Категорії будуть мати певний стандартний набір, пост має декілька категорій (до трьох) (додавання нових категорій передбачається в майбутньому) (Просто інформаційне
- Пуш нотіфікейшини без бази даних (Ярослав подивиться)
- Сортування (Найстаріші, найновіші) (додати дату створення поста в таблицю Posts), на майбутнє - додати каунтер перегляду конкретного посту (Поставити сортування по найновішому)
- В меню користувача "Оголошення" перейменувати в "Мої оголошення" і там буде таби з Створеними мною оголошеннями і Оголошення на які я відгукнувся. (це для користувача з роллю User)
-  Викинути Повідомлення з меню користувача (це для користувача з роллю User)
- Викинути Налаштування з меню користувача (це для користувача з роллю User)
- забрати пошук повідомлення з чату і у розгорнутому меню чату будуть "Вкладення" - показати усі медіа і "Видалити чат" (сторінка Чати)
- Основна інформація : Назва і категорії (обрати з основних), потім Опис, потім картинки (Сторінка Створення оголошень і Оголошення)
- Створити сторінку Оголошення коли відкриваєш на весь екран
- сторінка логування
- сторінка реєстрації

**Comment by KhilchenkoYurii** [comment]
@YaroslavKuziv1999 і ще треба панелька адміна де він зможе банити юзерів і оголошенню додати можливість видалення

**Comment by YaroslavKuziv1999** [comment]
> 

Done

**Comment by YaroslavKuziv1999** [comment]
> @YaroslavKuziv1999 зміни, будь ласко, в макеті назви на InterActiMate, якщо правильно пам.ятаю, то ми вирішили, що воно так більш читабельно буде

Done

**Comment by YaroslavKuziv1999** [comment]
> @YaroslavKuziv1999 Дороби будь ласка ось ці пункти
> 
> * Прибрати іконку будиночка (З усіх сторінок)
> * Забрати Кнопки Чат і Додати оголошення в Guest (Для сторінок де буде роль користувача Guest )
> * Категорії будуть мати певний стандартний набір, пост має декілька категорій (до трьох) (додавання нових категорій передбачається в майбутньому) (Просто інформаційне
> * Пуш нотіфікейшини без бази даних (Ярослав подивиться)
> * Сортування (Найстаріші, найновіші) (додати дату створення поста в таблицю Posts), на майбутнє - додати каунтер перегляду конкретного посту (Поставити сортування по найновішому)
> * В меню користувача "Оголошення" перейменувати в "Мої оголошення" і там буде таби з Створеними мною оголошеннями і Оголошення на які я відгукнувся. (це для користувача з роллю User)
> * Викинути Повідомлення з меню користувача (це для користувача з роллю User)
> * Викинути Налаштування з меню користувача (це для користувача з роллю User)
> * забрати пошук повідомлення з чату і у розгорнутому меню чату будуть "Вкладення" - показати усі медіа і "Видалити чат" (сторінка Чати)
> * Основна інформація : Назва і категорії (обрати з основних), потім Опис, потім картинки (Сторінка Створення оголошень і Оголошення)
> * Створити сторінку Оголошення коли відкриваєш на весь екран
> * сторінка логування
> * сторінка реєстрації

Done
